name: Release

on:
  push:
    branches:
      - master
      - develop

jobs:
  release:
    name: Release from monorepo
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: ğŸ§° Use Node.js 22.16.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: 'npm'

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: Bump version (main or develop)
        run: |
          if [ "${GITHUB_REF##*/}" = "master" ]; then
            echo "ğŸ“¦ Stable release"
            npx lerna version --conventional-commits --yes --no-push
          else
            echo "ğŸš§ Prerelease from develop"
            npx lerna version prerelease --preid dev --conventional-commits --yes --no-push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push version commit and tags
        run: git push origin HEAD --follow-tags

